### ISSUE TITLE
[IoT Vigilant / IoT Vigilant] Capturas de trafico

### ISSUE THREAD

**Issue by hasshido** [CybercampHackathon2018/ayuda#1]
**Hola Cybercamp!**
Con el objetivo de testear nuestros algoritmos contra muestras de tráfico diferentes, agradeceríamos que nos pasárais capturas de tráfico de vuestros propios laboratorios. ¡Gracias!

**Comment by grgut** [comment]
¡Aquí os dejamos una captura!
@hasshido 



[Prueba.txt](https://github.com/CybercampHackathon2018/ayuda/files/2629907/Prueba.txt)

**Comment by davidrasi** [comment]
> ¡Aquí os dejamos una captura!
> @hasshido
> 
> [Prueba.txt](https://github.com/CybercampHackathon2018/ayuda/files/2629907/Prueba.txt)

¡Estupendo! Muchas gracias por la captura, @UVaNoobs . No obstante, si pudiérais compartirnos una captura en una ventana de tiempo mucho más grande (10-20min) lo agradeceríamos mucho.

**Comment by grgut** [comment]
@hasshido 
Por ahora no podemos, ya que su tamaño supera los 10MB de tamaño máximo permitido por aquí.

**Comment by megavexus** [comment]
@iSecurity
Os adjunto algunas que tengo de archivo, son de dispositivos móviles únicamente, espero que os valgan.









[round1.pcap.txt](https://github.com/CybercampHackathon2018/ayuda/files/2630296/round1.pcap.txt)
[round3.pcap.txt](https://github.com/CybercampHackathon2018/ayuda/files/2630297/round3.pcap.txt)
[santander.pcap.txt](https://github.com/CybercampHackathon2018/ayuda/files/2630299/santander.pcap.txt)

**Comment by davidrasi** [comment]
> @hasshido
> Por ahora no podemos, ya que su tamaño supera los 10MB de tamaño máximo permitido por aquí.

Bueno, no os preocupeis compis, @UVaNoobs. Muchas gracias!

**Comment by davidrasi** [comment]
> @isecurity
> Os adjunto algunas que tengo de archivo, son de dispositivos móviles únicamente, espero que os valgan.
> 
> [round1.pcap.txt](https://github.com/CybercampHackathon2018/ayuda/files/2630296/round1.pcap.txt)
> [round3.pcap.txt](https://github.com/CybercampHackathon2018/ayuda/files/2630297/round3.pcap.txt)
> [santander.pcap.txt](https://github.com/CybercampHackathon2018/ayuda/files/2630299/santander.pcap.txt)

Genial! muchas gracias!

**Comment by yercito** [comment]
Buenas!

Aquí dejo un enlace con un montón de capturas de distintos dispositivos IoT, enchufes inteligentes, diversos sensores, cámaras, etc de la conferencia “IoT Sentinel: Automated Device-Type Identification for Security Enforcement in IoT,”. Yo las utilicé hace unos meses para un proyecto y me vinieron muy bien. 

https://research.aalto.fi/files/13004478/captures_IoT_Sentinel.zip

Espero que os sirva.

**Comment by davidrasi** [comment]
> Buenas!
> 
> Aquí dejo un enlace con un montón de capturas de distintos dispositivos IoT, enchufes inteligentes, diversos sensores, cámaras, etc de la conferencia “IoT Sentinel: Automated Device-Type Identification for Security Enforcement in IoT,”. Yo las utilicé hace unos meses para un proyecto y me vinieron muy bien.
> 
> https://research.aalto.fi/files/13004478/captures_IoT_Sentinel.zip
> 
> Espero que os sirva.

Buenas @yercito, genial. Muchas gracias. Sí nos puede servir. 
Un saludo!

**Comment by hasshido** [comment]
Cierro el issue, gracias por la colaboración! :smiley:
